import { CheckBox, Palette, TabWidget, ListView } from "std-widgets.slint";

import { TodoItem, OptionItem } from "../common.slint";
import { Callbacks } from "../callbacks.slint";

export component ItemBox inherits Rectangle {
    in-out property <TodoItem> item;
    in property <[OptionItem]> option_list;

    HorizontalLayout {
        width: 100%;
        CheckBox {
            width: 90%;
            toggled => {
                item.checked = self.checked;
            }
            text: item.title;
            checked: item.checked;
        }

        option_popup := PopupWindow {
            height: 150px;
            width: 100px;
            x: root.width - self.width;
            y: root.y + root.height + 1px;

            list_view := ListView {
                for option in option_list: Rectangle {
                    height: 30px;
                    width: 100px;
                    Text {
                        width: 100%;
                        text: option.title;
                    }

                    TouchArea {
                        clicked => {
                            Callbacks.option_action(option.action);
                        }
                    }
                }
            }
        }

        Rectangle {
            border-color: Palette.border;
            background: Palette.background;
            width: 10%;
            Text {
                text: "···";
                color: green;
            }

            TouchArea {
                clicked => {
                    option_popup.show();
                }
            }
        }
    }
}
