import {
    Button, CheckBox,  LineEdit,  ListView,HorizontalBox, VerticalBox,
    StandardButton, Palette, ComboBox, StandardListView, GroupBox
} from "std-widgets.slint";

import { TodoItem, OptionItem } from "common/struct.slint";
import { Callbacks } from "common/callbacks.slint";
import { ItemBox } from "left/item_list.slint";
import { AddPopup } from "left/add_popup.slint";

export component AppWindow inherits Window {
    min-width: 400px;
    min-height: 400px;
    in property <string> dt_text;
    in property <[OptionItem]> option_list;

    in-out property <[TodoItem]> todo_list;
    // 在此处注册 全局的 callbacks ;
    callback todo_add <=> Callbacks.todo_add;
    callback option_action <=> Callbacks.option_action;
    
    add_popup := AddPopup {
        width: min(self.preferred-width, root.width);
        height: min(self.preferred-height, root.height - 80px);
        x: (root.width - self.width) / 2;
        y: (root.height - self.height) / 2;
    }

    VerticalBox {
        height: 100%;
        width: 100%;
        Rectangle {
            padding: 5px;
            Text {
                horizontal-alignment: center;
                font-size: 22px;
                text: dt_text;
                color: darkblue;
            }
        }

        HorizontalLayout {
            height: 20px;
            width: 100%;
            Text {
                text: "Todo List:";
                color: orange;
            }

            Rectangle {
                width: 65%;
            }

            Button {
                text: "+";
                clicked => {
                    add_popup.show();
                }
            }
        }

        ListView {
            for item in root.todo_list: ItemBox {
                item: item;
                option_list: root.option_list;
            }
        }
    }
}
